-- =========================================================
-- FOOD SHOP DATABASE EXAMPLE
-- PostgreSQL / Supabase compatible
-- Example shop: "After Class Kitchen"
-- Currency: THB
-- =========================================================

-- Optional cleanup so the script can be run again
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

-- =========================================================
-- 1. CUSTOMERS
-- =========================================================
CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(120) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- 2. CATEGORIES
-- =========================================================
CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(80) NOT NULL UNIQUE
);

-- =========================================================
-- 3. MENU ITEMS
-- =========================================================
CREATE TABLE menu_items (
    menu_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL
        REFERENCES categories(category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    item_name VARCHAR(120) NOT NULL,
    description TEXT,
    price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- 4. ORDERS
-- =========================================================
CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT
        REFERENCES customers(customer_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    order_type VARCHAR(20) NOT NULL
        CHECK (order_type IN ('DINE_IN', 'TAKEAWAY', 'DELIVERY')),
    table_number VARCHAR(10),
    order_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (order_status IN ('PENDING', 'COOKING', 'READY', 'COMPLETED', 'CANCELLED')),
    subtotal NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_amount NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    delivery_fee NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
    total_amount NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    order_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- 5. ORDER ITEMS
-- Stores the price at the time of purchase.
-- This is important because menu prices can change later.
-- =========================================================
CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL
        REFERENCES orders(order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    menu_item_id BIGINT NOT NULL
        REFERENCES menu_items(menu_item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    note VARCHAR(255),
    line_total NUMERIC(10,2) GENERATED ALWAYS AS (quantity * unit_price) STORED
);

-- =========================================================
-- 6. PAYMENTS
-- =========================================================
CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL
        REFERENCES orders(order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    payment_method VARCHAR(20) NOT NULL
        CHECK (payment_method IN ('CASH', 'QR', 'CARD', 'TRANSFER')),
    amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PAID'
        CHECK (payment_status IN ('PENDING', 'PAID', 'REFUNDED')),
    paid_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- SAMPLE DATA
-- =========================================================

-- Customers
INSERT INTO customers (full_name, phone, email) VALUES
('Narin Chaiyaporn', '0812345678', 'narin@example.com'),
('Pimchanok Saelim', '0898765432', 'pim@example.com'),
('Thanawat Kittisak', '0861112233', 'thanawat@example.com'),
('Suphansa Meesuk', '0952223344', 'suphansa@example.com'),
('Krit Student', '0925557788', NULL);

-- Categories
INSERT INTO categories (category_name) VALUES
('Rice Dishes'),
('Noodles'),
('Side Dishes'),
('Drinks'),
('Desserts');

-- Menu
INSERT INTO menu_items
(category_id, item_name, description, price, is_available)
VALUES
(1, 'Pad Kra Pao Chicken with Rice', 'Thai basil chicken served with jasmine rice', 65.00, TRUE),
(1, 'Pad Kra Pao Pork with Rice', 'Thai basil pork served with jasmine rice', 65.00, TRUE),
(1, 'Garlic Pork with Rice', 'Stir-fried garlic pork with rice', 70.00, TRUE),
(1, 'Chicken Fried Rice', 'Classic Thai-style chicken fried rice', 65.00, TRUE),
(1, 'Omelet Rice', 'Crispy Thai omelet served over rice', 50.00, TRUE),
(2, 'Pad Thai Chicken', 'Thai stir-fried noodles with chicken', 75.00, TRUE),
(2, 'Spicy Instant Noodles', 'Spicy stir-fried instant noodles', 69.00, TRUE),
(3, 'Fried Chicken', 'Crispy fried chicken pieces', 59.00, TRUE),
(3, 'Fried Egg', 'Thai-style crispy fried egg', 15.00, TRUE),
(3, 'French Fries', 'Crispy salted french fries', 49.00, TRUE),
(4, 'Thai Iced Tea', 'Sweet Thai milk tea over ice', 45.00, TRUE),
(4, 'Iced Americano', 'Fresh espresso over ice', 50.00, TRUE),
(4, 'Cola', 'Chilled soft drink', 25.00, TRUE),
(4, 'Drinking Water', '600 ml bottled water', 15.00, TRUE),
(5, 'Toast with Condensed Milk', 'Crispy toast with sweet condensed milk', 39.00, TRUE);

-- =========================================================
-- ORDERS
-- =========================================================

-- Order #1
INSERT INTO orders
(customer_id, order_type, table_number, order_status,
 subtotal, discount_amount, delivery_fee, total_amount, order_date)
VALUES
(1, 'DINE_IN', 'A3', 'COMPLETED',
 125.00, 0.00, 0.00, 125.00, '2026-09-01 12:15:00+07');

INSERT INTO order_items
(order_id, menu_item_id, quantity, unit_price, note)
VALUES
(1, 1, 1, 65.00, 'Extra spicy'),
(1, 9, 1, 15.00, NULL),
(1, 11, 1, 45.00, 'Less sweet');

INSERT INTO payments
(order_id, payment_method, amount, payment_status, paid_at)
VALUES
(1, 'QR', 125.00, 'PAID', '2026-09-01 12:35:00+07');

-- Order #2
INSERT INTO orders
(customer_id, order_type, table_number, order_status,
 subtotal, discount_amount, delivery_fee, total_amount, order_date)
VALUES
(2, 'TAKEAWAY', NULL, 'COMPLETED',
 134.00, 10.00, 0.00, 124.00, '2026-09-01 17:40:00+07');

INSERT INTO order_items
(order_id, menu_item_id, quantity, unit_price, note)
VALUES
(2, 3, 1, 70.00, 'No coriander'),
(2, 10, 1, 49.00, NULL),
(2, 14, 1, 15.00, NULL);

INSERT INTO payments
(order_id, payment_method, amount, payment_status, paid_at)
VALUES
(2, 'CASH', 124.00, 'PAID', '2026-09-01 17:55:00+07');

-- Order #3
INSERT INTO orders
(customer_id, order_type, table_number, order_status,
 subtotal, discount_amount, delivery_fee, total_amount, order_date)
VALUES
(3, 'DELIVERY', NULL, 'COMPLETED',
 205.00, 0.00, 30.00, 235.00, '2026-09-02 19:05:00+07');

INSERT INTO order_items
(order_id, menu_item_id, quantity, unit_price, note)
VALUES
(3, 2, 2, 65.00, '1 normal, 1 spicy'),
(3, 8, 1, 59.00, NULL),
(3, 14, 1, 15.00, NULL);

INSERT INTO payments
(order_id, payment_method, amount, payment_status, paid_at)
VALUES
(3, 'TRANSFER', 235.00, 'PAID', '2026-09-02 19:06:00+07');

-- Order #4
INSERT INTO orders
(customer_id, order_type, table_number, order_status,
 subtotal, discount_amount, delivery_fee, total_amount, order_date)
VALUES
(4, 'DINE_IN', 'B2', 'COMPLETED',
 179.00, 0.00, 0.00, 179.00, '2026-09-03 13:20:00+07');

INSERT INTO order_items
(order_id, menu_item_id, quantity, unit_price, note)
VALUES
(4, 6, 1, 75.00, NULL),
(4, 8, 1, 59.00, NULL),
(4, 11, 1, 45.00, '50% sweet');

INSERT INTO payments
(order_id, payment_method, amount, payment_status, paid_at)
VALUES
(4, 'QR', 179.00, 'PAID', '2026-09-03 13:48:00+07');

-- Order #5
INSERT INTO orders
(customer_id, order_type, table_number, order_status,
 subtotal, discount_amount, delivery_fee, total_amount, order_date)
VALUES
(5, 'DINE_IN', 'A1', 'COOKING',
 154.00, 0.00, 0.00, 154.00, '2026-09-05 15:55:00+07');

INSERT INTO order_items
(order_id, menu_item_id, quantity, unit_price, note)
VALUES
(5, 7, 1, 69.00, 'Very spicy'),
(5, 11, 1, 45.00, 'Less ice'),
(5, 15, 1, 39.00, NULL);

-- =========================================================
-- USEFUL INDEXES
-- =========================================================
CREATE INDEX idx_menu_items_category_id
ON menu_items(category_id);

CREATE INDEX idx_orders_customer_id
ON orders(customer_id);

CREATE INDEX idx_orders_order_date
ON orders(order_date);

CREATE INDEX idx_order_items_order_id
ON order_items(order_id);

CREATE INDEX idx_order_items_menu_item_id
ON order_items(menu_item_id);

CREATE INDEX idx_payments_order_id
ON payments(order_id);

-- =========================================================
-- EXAMPLE SQL QUERIES
-- =========================================================

-- 1. Show all menu items
SELECT
    m.menu_item_id,
    c.category_name,
    m.item_name,
    m.price,
    m.is_available
FROM menu_items m
JOIN categories c
    ON c.category_id = m.category_id
ORDER BY c.category_name, m.item_name;

-- 2. Show complete order details
SELECT
    o.order_id,
    o.order_date,
    cu.full_name AS customer_name,
    o.order_type,
    o.order_status,
    m.item_name,
    oi.quantity,
    oi.unit_price,
    oi.line_total
FROM orders o
LEFT JOIN customers cu
    ON cu.customer_id = o.customer_id
JOIN order_items oi
    ON oi.order_id = o.order_id
JOIN menu_items m
    ON m.menu_item_id = oi.menu_item_id
ORDER BY o.order_id, oi.order_item_id;

-- 3. Calculate sales per order from order_items
SELECT
    o.order_id,
    SUM(oi.line_total) AS calculated_subtotal,
    o.discount_amount,
    o.delivery_fee,
    SUM(oi.line_total) - o.discount_amount + o.delivery_fee AS calculated_total
FROM orders o
JOIN order_items oi
    ON oi.order_id = o.order_id
GROUP BY
    o.order_id,
    o.discount_amount,
    o.delivery_fee
ORDER BY o.order_id;

-- 4. Top-selling menu items
SELECT
    m.item_name,
    SUM(oi.quantity) AS total_quantity_sold,
    SUM(oi.line_total) AS total_sales
FROM order_items oi
JOIN orders o
    ON o.order_id = oi.order_id
JOIN menu_items m
    ON m.menu_item_id = oi.menu_item_id
WHERE o.order_status = 'COMPLETED'
GROUP BY m.menu_item_id, m.item_name
ORDER BY total_quantity_sold DESC, total_sales DESC;

-- 5. Daily revenue
SELECT
    DATE(order_date AT TIME ZONE 'Asia/Bangkok') AS sales_date,
    COUNT(*) AS total_orders,
    SUM(total_amount) AS revenue
FROM orders
WHERE order_status = 'COMPLETED'
GROUP BY DATE(order_date AT TIME ZONE 'Asia/Bangkok')
ORDER BY sales_date;

-- 6. Revenue by payment method
SELECT
    payment_method,
    COUNT(*) AS payment_count,
    SUM(amount) AS total_amount
FROM payments
WHERE payment_status = 'PAID'
GROUP BY payment_method
ORDER BY total_amount DESC;

-- 7. Find orders from a specific customer
SELECT
    o.order_id,
    o.order_date,
    o.order_type,
    o.order_status,
    o.total_amount
FROM orders o
JOIN customers c
    ON c.customer_id = o.customer_id
WHERE c.full_name = 'Narin Chaiyaporn'
ORDER BY o.order_date DESC;

-- 8. Show available food under 70 THB
SELECT
    item_name,
    price
FROM menu_items
WHERE is_available = TRUE
  AND price < 70
ORDER BY price ASC;

-- 9. Update a menu price
-- UPDATE menu_items
-- SET price = 70.00
-- WHERE item_name = 'Pad Kra Pao Chicken with Rice';

-- 10. Mark an order as completed
-- UPDATE orders
-- SET order_status = 'COMPLETED'
-- WHERE order_id = 5;

-- 11. Delete a cancelled order
-- DELETE FROM orders
-- WHERE order_id = 5
--   AND order_status = 'CANCELLED';

-- =========================================================
-- OPTIONAL VIEW: ORDER SUMMARY
-- =========================================================
CREATE OR REPLACE VIEW order_summary AS
SELECT
    o.order_id,
    o.order_date,
    COALESCE(c.full_name, 'Walk-in Customer') AS customer_name,
    o.order_type,
    o.order_status,
    o.subtotal,
    o.discount_amount,
    o.delivery_fee,
    o.total_amount
FROM orders o
LEFT JOIN customers c
    ON c.customer_id = o.customer_id;

-- Example:
SELECT * FROM order_summary ORDER BY order_id;

-- =========================================================
-- END OF FILE
-- =========================================================
